name: Pipeline
on:
  push:
    branches: [main]
jobs:
  docket_hub:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
      
    - name: Docker login
      uses: docker/login-action@v3.1.0
      with:
        username: lucasfm95
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
    - name: Build and Push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        tags: 'lucasfm95/fiap-github-actions:latest'
        push: true
  release:
    needs:
      - docket_hub
    environment:
      name: production
    name: Ready to deploy ?
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  
  approval-gate:
    name: Deploy on render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - release
    steps:
      - name: Send deploy render
        uses: Tyrrrz/action-http-request@1.1.2
        with:
          url:  https://api.render.com/deploy/${{ secrets.DEPLOY_RENDER }}
